replacements:
  "ko": "không"
  "k": "không"
  "kg": "không"
  "khong": "không"
  "ban": "bẩn"
  "dơ": "bẩn"
  "dirty": "bẩn"
  "sold out": "hết món"
  "parking": "gửi xe"
  "30p": "30 phút"
  "nửa tiếng": "30 phút"
